version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fitness_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: boss
      MYSQL_PASSWORD: boss123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fitness_network

volumes:
  mysql_data:

networks:
  fitness_network:
    driver: bridge