// <auto-generated />
using System;
using FitnessApp.Infrastructure.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218181658_InitialCreateWithSubscriptions")]
    partial class InitialCreateWithSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("idx_benefit_display_name");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_benefit_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_benefit_name");

                    b.ToTable("benefits", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.BenefitPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleWeekday")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("schedule_weekday");

                    b.Property<string>("ScheduleWeekend")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("schedule_weekend");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_benefit_package_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_benefit_package_name");

                    b.ToTable("benefit_packages", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.BenefitPackageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BenefitId")
                        .HasColumnType("int")
                        .HasColumnName("benefit_id");

                    b.Property<int>("BenefitPackageId")
                        .HasColumnType("int")
                        .HasColumnName("benefit_package_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId")
                        .HasDatabaseName("idx_benefit_package_item_benefit");

                    b.HasIndex("BenefitPackageId")
                        .HasDatabaseName("idx_benefit_package_item_package");

                    b.HasIndex("BenefitPackageId", "BenefitId")
                        .IsUnique()
                        .HasDatabaseName("idx_benefit_package_item_unique");

                    b.ToTable("benefit_package_items", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("InstallmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("installment_number");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("idx_payment_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_payment_status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("idx_payment_subscription");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("idx_payment_transaction_unique")
                        .HasFilter("transaction_id IS NOT NULL");

                    b.HasIndex("SubscriptionId", "InstallmentNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_payment_installment_unique");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_subscription_client");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("idx_subscription_end_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_subscription_status");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("idx_subscription_plan");

                    b.HasIndex("ClientId", "SubscriptionPlanId", "Status")
                        .HasDatabaseName("idx_subscription_client_plan_status");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AllowInstallments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_installments");

                    b.Property<int>("BenefitPackageId")
                        .HasColumnType("int")
                        .HasColumnName("benefit_package_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int")
                        .HasColumnName("duration_months");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring");

                    b.Property<int>("MaxInstallments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_installments");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BenefitPackageId")
                        .HasDatabaseName("idx_subscription_plan_benefit_package");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_subscription_plan_is_active");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_subscription_plan_type");

                    b.HasIndex("Type", "BenefitPackageId", "IsActive")
                        .HasDatabaseName("idx_subscription_plan_type_package_active");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(5.0m)
                        .HasColumnName("rating");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.BenefitPackageItem", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Subscriptions.Benefit", "Benefit")
                        .WithMany("BenefitPackageItems")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Domain.Entities.Subscriptions.BenefitPackage", "BenefitPackage")
                        .WithMany("BenefitPackageItems")
                        .HasForeignKey("BenefitPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("BenefitPackage");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Payment", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Subscriptions.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Users.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Domain.Entities.Subscriptions.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.SubscriptionPlan", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Subscriptions.BenefitPackage", "BenefitPackage")
                        .WithMany("SubscriptionPlans")
                        .HasForeignKey("BenefitPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenefitPackage");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.Client", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Users.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("FitnessApp.Domain.Entities.Users.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.Trainer", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Users.User", "user")
                        .WithOne("TrainerProfile")
                        .HasForeignKey("FitnessApp.Domain.Entities.Users.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Benefit", b =>
                {
                    b.Navigation("BenefitPackageItems");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.BenefitPackage", b =>
                {
                    b.Navigation("BenefitPackageItems");

                    b.Navigation("SubscriptionPlans");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.Client", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("TrainerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
